spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpa-shop
    username: sa
    password:
    driver-class-name: org.h2.Driver
    
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true 콘솔창에 출력됨
        format_sql: true

logging.level:
  org.hibernate.sql: debug
  org.hibernate.orm.jdbc.bind: trace

      